<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV9pQg8F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV9pQg8F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV9pQg8F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV9pQg8F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV9pQg8F\App_KernelDevDebugContainer([
    'container.build_hash' => 'V9pQg8F',
    'container.build_id' => '9d2f0afa',
    'container.build_time' => 1684922898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV9pQg8F');
