<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNVtxpVa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNVtxpVa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNVtxpVa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNVtxpVa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNVtxpVa\App_KernelDevDebugContainer([
    'container.build_hash' => 'NVtxpVa',
    'container.build_id' => '888ef24b',
    'container.build_time' => 1684935859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNVtxpVa');
