<?php

namespace ContainerNVtxpVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LJdBBbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lJdBBb_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lJdBBb_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\RecordRepository', 'getRecordRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\RecordRepository',
        ]);
    }
}
