<?php

namespace ContainerNVtxpVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RecordRepository' shared autowired service.
     *
     * @return \App\Repository\RecordRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/RecordRepository.php';

        return $container->privates['App\\Repository\\RecordRepository'] = new \App\Repository\RecordRepository();
    }
}
